# Generated by Django 5.0.8 on 2024-09-17 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_point', '0002_game_systemrequirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игру', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='systemrequirement',
            options={'verbose_name': 'Системные требования', 'verbose_name_plural': 'Системные требования'},
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrior_point.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='game',
            name='content',
            field=models.TextField(verbose_name='Опсиание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='game',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='game',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='systemrequirement',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrior_point.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='systemrequirement',
            name='memory',
            field=models.CharField(max_length=255, verbose_name='Память'),
        ),
        migrations.AlterField(
            model_name='systemrequirement',
            name='op_system',
            field=models.CharField(max_length=255, verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='systemrequirement',
            name='processor',
            field=models.CharField(max_length=255, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='systemrequirement',
            name='ram',
            field=models.CharField(max_length=255, verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='systemrequirement',
            name='video_card',
            field=models.CharField(max_length=255, verbose_name='Видео карта'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('created_ad', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrior_point.game', verbose_name='Игруля')),
                ('user', models.ForeignKey(blank=True, default='user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарии',
                'verbose_name_plural': 'Комментарий',
            },
        ),
    ]
