# Generated by Django 5.0.8 on 2024-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_point', '0004_rename_created_ad_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='torrent',
            field=models.FileField(blank=True, null=True, upload_to='torrents', verbose_name='Торрент файлы'),
        ),
    ]
