# Generated by Django 5.0.8 on 2024-09-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_point', '0005_game_torrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='torrent',
            field=models.FileField(blank=True, null=True, upload_to='torrents/', verbose_name='Торрент файлы'),
        ),
    ]
