# Generated by Django 5.0.8 on 2024-10-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_point', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=150, verbose_name='Апи пользователя')),
            ],
            options={
                'verbose_name': 'Ip пользователя',
                'verbose_name_plural': 'Ip пользователей',
            },
        ),
        migrations.RemoveField(
            model_name='game',
            name='views',
        ),
        migrations.AddField(
            model_name='game',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, related_name='game_views', to='warrior_point.ip', verbose_name='Просмотры'),
        ),
    ]
