# Generated by Django 5.0.8 on 2024-10-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_point', '0008_ip_remove_game_views_game_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='game_views', to='warrior_point.ip', verbose_name='Просмотры'),
        ),
    ]
